Module 1
jurica-zecevic/react pull request #1
Opened 2023-08-10 14:08 UTC by jurica-zecevic

2023-08-15 12:43 UTC, evasimonyi requested changes
- please simplify CSS rules. End result is nice, but the amount of CSS selectors and rules are overwhelming. There are a lot of unnecessary classes (use tag selectors!) and rules. It is a lot, regarding how small the app is, and how few components there are
- pay attention to naming, left, right, boldPart, notBoldPart, leftSomething, these kind of classes are not recommended. Instead: `listItem`, `buttonContainer`, `courseDetails`, `cardHeader`, etc.
- logic should be separated to helper files


nice work overall, but please check my notes and make some changes! :)

2023-08-15 12:43 UTC, evasimonyi commented on src/index.css
> +html,
why overwrite built-in styling? never seen this before :D I don't suggest this
they are very useful! you use margins on headings, and p tags in your css files that are totally unnecessary if you just keep default styling

2023-08-15 12:43 UTC, evasimonyi commented on src/components/Courses/components/SearchBar/SearchBar.jsx
> +	}, [searchQuery, onSearch]);
why is this necessary? what does it do that `handleSubmit` does not?

2023-08-15 12:43 UTC, evasimonyi commented on src/components/Header/Header.jsx
> +import React from 'react';
```suggestion
```



from React 17 it is not necessary anymore to import React, only useEffect, useState etc, but this import is not needed!

https://dev.to/titungdup/you-no-longer-need-to-import-react-from-react-3pbj

2023-08-15 12:43 UTC, evasimonyi commented on src/components/Courses/components/EmptyCourseList/EmptyCourseList.jsx
> +		<section className={styles.empty}>
unnecessary class, use `section` tag selector

2023-08-15 12:43 UTC, evasimonyi commented on src/components/Courses/components/EmptyCourseList/EmptyCourseList.module.css
> +.empty button {
you could use flex on parent container, and use gap to make sure spacing between title, paragraph and button are equal
optional of course

2023-08-15 12:43 UTC, evasimonyi commented on src/components/Courses/components/CourseInfo/CourseInfo.jsx
> +	const formatDuration = (durationInMinutes) => {
nice, clear util method!

2023-08-15 12:43 UTC, evasimonyi commented on src/App.jsx
> +			<main>
this main is unnecessary
please use main instead of div in Container, and delete this main wrapper
this is an extra node in the DOM tree that does nothing, not good for performance!

2023-08-15 13:46 UTC, jurica-zecevic commented on src/common/Button/Button.jsx
> +			{children}
Understood, done

2023-08-15 13:47 UTC, jurica-zecevic commented on src/common/Button/Button.module.css
> +}
VS Code + Prettier

2023-08-15 13:47 UTC, jurica-zecevic commented on src/common/Container/Container.module.css
> +  padding-right: 16px;
Done

2023-08-15 13:47 UTC, jurica-zecevic commented on src/common/Container/Container.module.css
> +    padding-right: 24px;
Done

2023-08-15 13:47 UTC, jurica-zecevic commented on src/components/Courses/Courses.jsx
> +			{/* <Button type='button'>Add new course</Button> */}
Understood, uncommented

2023-08-15 13:47 UTC, jurica-zecevic commented on src/components/Header/Header.jsx
> +import React from 'react';
Nice, wasn't aware of this

2023-08-15 13:49 UTC, jurica-zecevic commented on src/components/Courses/components/EmptyCourseList/EmptyCourseList.jsx
> +		<section className={styles.empty}>
Dont really understand how to use CSS modules in React, delete this class and use tag selectors. Wouldn't tag selector be a global rule than?

2023-08-15 13:50 UTC, jurica-zecevic commented on src/components/Courses/components/EmptyCourseList/EmptyCourseList.module.css
> +.empty button {
Done. It made button increase in width because parent is set to flex, but a simple align-self on button did the trick. Sure, this helps with same spacings between items, but in the design, there is a different spacing for text and button

2023-08-15 13:52 UTC, jurica-zecevic commented on src/App.jsx
> +			<main>
If you take a look in "index.css", you will notice main tag selector and using flex on it to always take full view-height of it's parent (body). This way, in case of small amount of content, <main> always takes available space

2023-08-15 15:58 UTC, jurica-zecevic commented on src/index.css
> +html,
We are always using some kind of CSS reset to get cross-browser support.  I agree , but in pixel perfect designs, these default styling just might not do the trick :D 
Removed them, now my paragraphs have top margin by default which is not the case in Figma. This means I still need to go with component specific CSS

2023-08-15 15:59 UTC, jurica-zecevic commented on src/components/Courses/components/SearchBar/SearchBar.jsx
> +	}, [searchQuery, onSearch]);
This one is if you search for something -> get result -> start deleting search term and when all characters are deleted, search resets

2023-08-15 16:04 UTC, jurica-zecevic commented on src/components/Header/Header.module.css
> +  justify-content: space-between;
If user is not authorized, <span> element is not rendered to the DOM, thus button sticks to the left, right after the logo

2023-08-15 16:11 UTC, jurica-zecevic commented on src/components/Courses/components/CourseInfo/CourseInfo.module.css
> +  padding-top: 48px;
![1](https://github.com/jurica-zecevic/react/assets/51235635/370d1ae4-15a3-438a-ad45-30159fc196ed)
Design is like this. There is no design for mobile nor it is mentioned anywhere to handle it. Will do!

2023-08-15 16:57 UTC, jurica-zecevic commented on src/components/Courses/components/SearchBar/SearchBar.jsx
> +		<form onSubmit={handleSubmit} className={styles.form}>
Why notuse custom class. Perhaps at a later stage, I will need form on a different place. Isn't it good practice to think ahead?

2023-08-15 16:59 UTC, jurica-zecevic commented on src/components/Courses/components/CourseCard/CourseCard.jsx
> +		const date = creationDate.split('/');
replace with regex... :D

2023-08-15 17:02 UTC, jurica-zecevic commented on src/components/Courses/components/CourseInfo/CourseInfo.module.css
> +  font-weight: 700;
Maybe on Chrome, but there are possible variations on other browsers

2023-08-15 17:04 UTC, jurica-zecevic commented on src/components/Courses/components/CourseCard/CourseCard.module.css
> +  margin-right: 48px;
Rarely used gap since it has 93.94% global coverage

2023-08-15 17:06 UTC, jurica-zecevic commented on src/components/Courses/components/CourseCard/CourseCard.module.css
> +  width: 33.33%;
Got used to use percentages since calc 95.85% and client mostly demand more

2023-08-15 18:51 UTC, evasimonyi reviewed
most of them were suggestions anyway, I'm glad that you answered, the point is just to have a discussion, and maybe I hope to give some useful suggestions :)

I tried to fix my mistake with the classnames by adding suggestions you'd just have to accept and git will commit them immediately

also please check the folder structure, it has some mistakes in it!
https://d17btkcdsmqrmh.cloudfront.net/react-fundamentals/docs/module-1/home-task/task

point 5. here

2023-08-15 18:51 UTC, evasimonyi commented on src/App.jsx
> +
you overcomplicated it a little bit

this is fine, so no need to change, but if you're interested in a simpler solution for the future:

```js
<Container>
				{mockedCoursesList.length === 0 && <EmptyCourseList />}
				{mockedCoursesList.length > 0 &&
					(selectedCourse ? (
						<CourseInfo
							{...selectedCourse}
					    authorsList={mockedAuthorsList}
					    onBackToCourses={handleCourseInfo}
						/>
					) : (
						<Courses
							coursesList={mockedCoursesList}
					    authorsList={mockedAuthorsList}
					    onSelectCourse={handleCourseInfo}
						/>
					))}
			</Container>
```

2023-08-15 18:51 UTC, evasimonyi commented on src/App.jsx
> +	const handleCourseInfo = (course) => {
yes, great!

2023-08-15 18:51 UTC, evasimonyi commented on src/components/Courses/components/CourseCard/CourseCard.jsx
> +							Duration: {formatCourseDuration(duration).durationTime}{' '}
nice solution
first one was also great:
`${formattedHours}:${formattedMinutes} ${hourString}`;

but this is good for another reason :)

(in the future I would split it further, for 2 separate methods, because one method should do only one thing)

2023-08-15 18:51 UTC, evasimonyi commented on src/helpers/formatCreationDate.js
> +export const formatCreationDate = (creationDate) => {
great!

(a more simple one:)
```suggestion
export const formatCreationDate = (creationDate) => creationDate.replaceAll(/\//g, '.');
```

are you familiar with this syntax? if it is only one line, you can immediately return it

2023-08-15 18:51 UTC, evasimonyi commented on src/components/Courses/components/CourseInfo/CourseInfo.jsx
> +							<span className={styles.itemLeft}>ID: </span>
great naming now!

2023-08-15 18:51 UTC, evasimonyi commented on src/components/Courses/components/CourseCard/CourseCard.module.css
> +  margin-right: 48px;
not detectable for human eyes, but still :D 
(fine by me, these are mostly just suggestions)

2023-08-15 18:51 UTC, evasimonyi commented on src/components/Header/Header.module.css
> +  justify-content: space-between;
great!

2023-08-15 18:51 UTC, evasimonyi commented on src/components/Courses/components/CourseCard/CourseCard.module.css
> +  width: 33.33%;
I can accept, thanks for the explanation behind it! :)

2023-08-15 18:51 UTC, evasimonyi commented on src/index.css
> +html,
you can overwrite default margins wherever it is needed of course, but most of the time default margins will be enough
you can totally leave them if you'd like, I am open to these discussions!

2023-08-15 18:51 UTC, evasimonyi commented on src/components/Courses/components/EmptyCourseList/EmptyCourseList.module.css
> +.empty button {
I'm sorry I missed that, I was just checking the end result, but the main design is more important, so whatever you'd like:)
the home task end result pixels are nice if they match, I just suggest different solutions, so you don't have to take them all, just FYI, use them in the future if you'd like

2023-08-15 18:51 UTC, evasimonyi commented on src/components/Courses/components/SearchBar/SearchBar.jsx
> +	}, [searchQuery, onSearch]);
I would not expect this behaviour as a user
what if I search for javascript, click on the button,
then I want to search for angular, empty the field, and then a change happens, and it deletes my previous search

I would only expect filtering after I click on the Search button

2023-08-15 18:51 UTC, evasimonyi commented on src/components/Courses/components/SearchBar/SearchBar.jsx
> +		<form onSubmit={handleSubmit} className={styles.form}>
yes, absolutely! please leave it

2023-08-15 18:51 UTC, evasimonyi commented on src/components/Courses/components/SearchBar/SearchBar.module.css
> +}
this is still missing, some linters will give warning
(if yours not, this is not crucial)

2023-08-15 18:51 UTC, evasimonyi commented on src/components/Header/components/Logo/Logo.module.css
> +}
missing end of file line

2023-08-15 18:51 UTC, evasimonyi commented on src/common/Input/Input.module.css
> +input {
you were right the first time, sorry!
```suggestion
.input {
```

2023-08-15 18:51 UTC, evasimonyi commented on src/common/Input/Input.module.css
> +  input {
```suggestion
  .input {
```

2023-08-15 18:51 UTC, evasimonyi commented on src/components/Courses/components/SearchBar/SearchBar.module.css
> +form {
```suggestion
.form {
```

2023-08-15 18:51 UTC, evasimonyi commented on src/components/Courses/components/SearchBar/SearchBar.module.css
> +form input {
```suggestion
.form input {
```

2023-08-15 18:51 UTC, evasimonyi commented on src/common/Button/Button.module.css
> +  button {
```suggestion
  .button {
```

2023-08-15 18:51 UTC, evasimonyi commented on src/common/Button/Button.module.css
> +button:hover {
```suggestion
.button:hover {
```

2023-08-15 18:51 UTC, evasimonyi commented on src/common/Input/Input.module.css
> +input:focus {
```suggestion
.input:focus {
```

2023-08-15 18:51 UTC, evasimonyi commented on src/components/Header/Header.module.css
> +header {
```suggestion
.header {
```

2023-08-15 18:51 UTC, evasimonyi commented on src/components/Header/Header.module.css
> +  header {
```suggestion
  .header {
```

2023-08-16 08:48 UTC, evasimonyi approved these changes
Great job! 🥇  :)

2023-08-16 08:48 UTC, evasimonyi commented on src/components/Courses/components/SearchBar/SearchBar.jsx
> +	}, [searchQuery, onSearch]);
maybe I misunderstood then... I thought it indicated that the user clicks on Search too, because in previous exercises search query was updated only on click
but you are right, it is not explicitly asks for button click!

2023-08-16 08:52 UTC, merged