Module 3 state management
jurica-zecevic/react pull request #3
Opened 2023-08-24 13:07 UTC by jurica-zecevic

2023-08-28 21:39 UTC, evasimonyi requested changes
- why didn't you use redux toolkit? I was expecting `createSlice`-s
- naming convention for action creators: `saveAuthor`, `getCourse`, no need to add 'Action' to the end, repetitive, adds no info (but if you prefer it this way, no need to delete 'Action' part)
- great solution! 👍

2023-08-28 21:39 UTC, evasimonyi commented on src/store/courses/reducer.js
> +	}
don't you want to try out redux-toolkit's `createSlices` instead of "pure" redux reducers?
this is also fine, so not necessary
but in the future is suggest to practice redux toolkit, even if you prefer this way, because you probably have to use it someday, it is **very** popular, and official redux team strongly suggests using it:
https://redux.js.org/style-guide/#use-redux-toolkit-for-writing-redux-logic

2023-08-28 21:39 UTC, evasimonyi commented on src/store/user/reducer.js
> +	token: localStorage.getItem('token') || '',
since isAuth is false, there is no name and email in the initial state, for me it's more logical that initial token is empty. why did you set it from localstorage?

2023-08-28 21:39 UTC, evasimonyi commented on src/store/authors/reducer.js
> +		case actions.SAVE_AUTHORS:
```suggestion
		case actions.SAVE_AUTHOR:
```
you are adding one at a time, so singular

2023-08-29 07:04 UTC, jurica-zecevic commented on src/App.jsx
> +					element={<Courses coursesList={courses} authorsList={authors} />}
I prefer to have it in App.jsx since I already have everything in place in the components

2023-08-29 08:00 UTC, jurica-zecevic commented on src/store/courses/reducer.js
> +	}
Well, I was just following the course. If I use createSlices, I need to not use CreateStore. Also, than don't need actions, reducer, types.js files, thus not following the folder structure of the course

2023-08-29 08:05 UTC, jurica-zecevic commented on src/components/CreateCourse/CreateCourse.jsx
>  	const [authors, setAuthors] = useState([]);
"that here you should list all existing authors (accessed from the store), and be able to add them to course authors section" - I don't think so. There is nothing to access from the store if this is creation of a new course and new author(s)...

2023-08-29 12:51 UTC, evasimonyi commented on src/components/CreateCourse/CreateCourse.jsx
>  	const [authors, setAuthors] = useState([]);
I mean in the second home task, I think we should list al authors here
But it is not a requirement in this module

![2023-08-29_14h50_29](https://github.com/jurica-zecevic/react/assets/30794349/8987d9fb-3de1-419a-afef-0be7662011e0)

2023-08-29 12:55 UTC, jurica-zecevic commented on src/components/CreateCourse/CreateCourse.jsx
>  	const [authors, setAuthors] = useState([]);
Ah yes, now I see it :)

2023-08-29 12:58 UTC, evasimonyi commented on src/store/courses/reducer.js
> +	}
I could not update the course in time :( I thought you will use redux toolkit documentation
but according to the task description, this is the correct one

2023-08-29 13:29 UTC, evasimonyi approved these changes

2023-08-29 13:30 UTC, merged